import turtle
turtle.Screen().bgcolor("blue")
turtle.Screen().setup(1000,1000)
rectangle=turtle.Turtle()
rectangle.forward(300)
rectangle.left(90)
rectangle.forward(400)
rectangle.left(90)
rectangle.forward(300)
rectangle.left(90)
rectangle.forward(400)
turtle.done()